[functions]
  [functions.on-video-upload]
    timeout = 60
  [functions.analyze-chunk]
    timeout = 60
  [functions.generate-music]
    timeout = 300
  [functions.generate-sfx-batch]
    timeout = 300
  [functions.finalize-project]
    timeout = 60
